import Navbar from "./_components/_layouts/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "Hitung",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative w-full flex items-center justify-center">
          <Navbar className="top-2" />
          {/* <p className="text-black dark:text-white"> */}
          {children}
          {/* </p> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}